### ISSUE TITLE
File not found error in Docker Windows

### ISSUE THREAD

**Issue by mrchief** [alexjc/neural-enhance#104]
I tried:

`docker run --rm -v `pwd`:/ne/input -it alexjc/neural-enhance .\test.jpg` 

and I get a File not found error:

```
  _ __   ___ _   _ _ __ __ _| |   ___ _ __ | |__   __ _ _ __   ___ ___
 | '_ \ / _ \ | | | '__/ _` | |  / _ \ '_ \| '_ \ / _` | '_ \ / __/ _ \
 | | | |  __/ |_| | | | (_| | | |  __/ | | | | | | (_| | | | | (_|  __/
 |_| |_|\___|\__,_|_|  \__,_|_|  \___|_| |_|_| |_|\__,_|_| |_|\___\___|

Super Resolution for images and videos powered by Deep Learning!
  - Code licensed as AGPLv3, models under CC BY-NC-SA.
  - Using the device `cpu` for neural computation.

Enhancing 1 image(s) specified on the command-line.
  - Loaded file `ne2x-photo-default-0.3.pkl.bz2` with trained model.

.\test.jpg Traceback (most recent call last):
  File "enhance.py", line 583, in <module>
    img = scipy.ndimage.imread(filename, mode='RGB')
  File "/opt/conda/lib/python3.5/site-packages/scipy/ndimage/io.py", line 24, in imread
    return _imread(fname, flatten, mode)
  File "/opt/conda/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/conda/lib/python3.5/site-packages/PIL/Image.py", line 2282, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '.\\test.jpg'
```

The alias command also doesn't work on Windows.

I looked at readme and related issues but I think they are mixing Windows/*Nix stuff. A clear example for Windows may help alleviate this issue.

**Comment by alexjc** [comment]
I haven't tested on Windows. Try replacing `pwd` with your current directory with an absolute path (ideally within `C:\Users\<username>\`), then removing `.\` from `test.jpg`. Once you get it working let me know and I can update the README — or you can make a PR if you want ;-)

**Comment by mrchief** [comment]
Tried all those. And exact same error in both cases. If i bash into the image and do an `ls input`, I see no files there even though the local folder has test.jpg.

**Comment by geraldblank** [comment]
Alex: I am having a similar issue as mrchief. 
I also need a clearer example of how to use Docker with Neural-Enhance in Windows 10 x64.

I have successfully created a .bashrc file containing the "alias enhance..." script on your page.
I believe the info we need now are the steps one must take afterward:

1. Where the .bashrc folder should be located, and
2. How to verify that the script is properly loaded in Kitematic's/Docker's command line interface.

This is a great project! Thanks in advance for your help.

**Comment by alexjc** [comment]
I don't have time to look into this issue on Windows right now (it's not my native OS).  I find Docker's support of Windows abrasive at best (it rarely works out of the box), these issues should be explained in the docker documentation somewhere? If anyone finds them, please post help here or make a PR.

**Comment by mrchief** [comment]
@alexjc I'm with you on Docker. Its a big pain to get anything right and their documentation is all over the place.

Could you please explain what steps need to be done? Maybe we can ditch docker and try it using native tools/frameworks on Windows.

I'm thinking all steps in [manual installation](https://github.com/alexjc/neural-enhance#2b-manual-installation-developers) and then `enhance.py test.jpg`?

**Comment by alexjc** [comment]
Installation on Windows is rather difficult, even for experts it takes a while and is error prone. The only problem with Docker is figuring out how/where the paths are mounted. Usually mounting within `C:\Users\<username>\` helps but apparently not here... I'd look in the docs for windows mounts and see if anything has changed.

**Comment by mrchief** [comment]
I had to share a folder using docker toolbox. Even <username>. After that I was able to mount it. But it doesn't see any files in there. I'll keep looking.

**Comment by LNFWebsite** [comment]
Try this solution...

https://github.com/alexjc/neural-enhance/issues/59#issuecomment-259397623

**Comment by mrchief** [comment]
Not sure what this path means:

`cp /ns/Users/(My User)/ne2x-large-0.2.pkl.bz2 /ne`

**Comment by LNFWebsite** [comment]
@mrchief Sorry for the delay... That command is for copying a larger dataset into the docker environment for usage in neural-enhance. It's because this comment was for a different issue involving adding a larger (or newer) library.

You may just ignore that line.

**Comment by geraldblank** [comment]
@LNFWebsite This did the trick for me, thanks much for your help!
The scripts now run properly on Docker for Windows. I am running Windows 10 x64.
**NOTE** for other Windows users: I am able to use pathnames with spaces ONLY if the path/file name is enclosed in a pair of quotation marks.

**Comment by LNFWebsite** [comment]
Your welcome! Glad to hear you got it working!
