### ISSUE TITLE
`No such file or directory` with the input images

### ISSUE THREAD

**Issue by nkint** [alexjc/neural-enhance#107]
Hi
following the readme:

Mac OS/X 10.12.1
Docker version 1.12.3, build 6b644ec

```
docker run --rm -v `pwd`:/ne/input -it alexjc/neural-enhance --help
```

Ok, nice

```
alias enhance='function ne() { docker run --rm -v "$(pwd)/`dirname ${@:$#}`":/ne/input -it alexjc/neural-enhance ${@:1:$#-1} "input/`basename ${@:$#}`"; }; ne'

enhance --zoom=1 --model=repair Desktop/image.jpg
```

got this:

```
enhance --zoom=1 --model=repair Desktop/image.jpg
                             _              _                           
  _ __   ___ _   _ _ __ __ _| |   ___ _ __ | |__   __ _ _ __   ___ ___  
 | '_ \ / _ \ | | | '__/ _` | |  / _ \ '_ \| '_ \ / _` | '_ \ / __/ _ \ 
 | | | |  __/ |_| | | | (_| | | |  __/ | | | | | | (_| | | | | (_|  __/ 
 |_| |_|\___|\__,_|_|  \__,_|_|  \___|_| |_|_| |_|\__,_|_| |_|\___\___| 

Super Resolution for images and videos powered by Deep Learning!
  - Code licensed as AGPLv3, models under CC BY-NC-SA.
  - Using the device `cpu` for neural computation.

Enhancing 2 image(s) specified on the command-line.
  - Loaded file `ne1x-photo-repair-0.3.pkl.bz2` with trained model.

Desktop/Puglia_Franco-Fontana_1978.jpg Traceback (most recent call last):
  File "enhance.py", line 583, in <module>
    img = scipy.ndimage.imread(filename, mode='RGB')
  File "/opt/conda/lib/python3.5/site-packages/scipy/ndimage/io.py", line 24, in imread
    return _imread(fname, flatten, mode)
  File "/opt/conda/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/conda/lib/python3.5/site-packages/PIL/Image.py", line 2282, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'Desktop/image.jpg'
```

where do I have to put my images? Is there something wrong?

**Comment by nkint** [comment]
Resolved. Should be a bug in Hyper term with zsh
With iTerm and bash it works.

**Comment by alexjc** [comment]
Does iTerm and zsh work? It should, if not the alias may need fixing...

**Comment by vlebourl** [comment]
iTerm and zsh doesn't work... same error.
