### ISSUE TITLE
argparse.ArgumentError: argument --model: conflicting option string: --model

### ISSUE THREAD

**Issue by ssccsscc** [alexjc/neural-enhance#13]
Traceback (most recent call last):
  File "enhance.py", line 40, in <module>
    add_arg('--model',              default='small', type=str,          help='Name of the neural network to load/save.')
  File "C:\Lasagne\WinPython\python-3.4.4.amd64\lib\argparse.py", line 1349, in add_argument
    return self._add_action(action)
  File "C:\Lasagne\WinPython\python-3.4.4.amd64\lib\argparse.py", line 1709, in _add_action
    self._optionals._add_action(action)
  File "C:\Lasagne\WinPython\python-3.4.4.amd64\lib\argparse.py", line 1553, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "C:\Lasagne\WinPython\python-3.4.4.amd64\lib\argparse.py", line 1363, in _add_action
    self._check_conflict(action)
  File "C:\Lasagne\WinPython\python-3.4.4.amd64\lib\argparse.py", line 1502, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "C:\Lasagne\WinPython\python-3.4.4.amd64\lib\argparse.py", line 1511, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --model: conflicting option string: --model

**Comment by Aidenjl193** [comment]
Yeah, line 39 in enhance.py needs removing to fix this

**Comment by Dikay900** [comment]
fixed with #10
