### ISSUE TITLE
RuntimeError: CorrMM failed to allocate working memory of 1600 x 1048576

### ISSUE THREAD

**Issue by XPanniX** [alexjc/neural-enhance#14]
I installed everything manually and try to process a 256x256 JPG image.
When running the enhance command without any additional parameters I get the following error:

```
Enhancing 1 image(s) specified on the command-line.
  - Loaded file `ne4x-small-0.1.pkl.bz2` with trained model.                                                                                                

img.jpg
Traceback (most recent call last):
  File "/home/jan/neural-enhance/pyvenv/lib/python3.5/site-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
RuntimeError: CorrMM failed to allocate working memory of 1600 x 1048576


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "enhance.py", line 511, in <module>
    out = enhancer.process(scipy.ndimage.imread(filename, mode='RGB'))
  File "enhance.py", line 498, in process
    *_, repro = self.model.predict(img)
  File "/home/jan/neural-enhance/pyvenv/lib/python3.5/site-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/jan/neural-enhance/pyvenv/lib/python3.5/site-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/jan/neural-enhance/pyvenv/lib/python3.5/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/jan/neural-enhance/pyvenv/lib/python3.5/site-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
RuntimeError: CorrMM failed to allocate working memory of 1600 x 1048576

Apply node that caused the error: CorrMM{(2, 2), (1, 1)}(Elemwise{Composite{(((i0 + i1) * i2 * i3) + (Abs((i0 + i1)) * i2 * i4))}}[(0, 0)].0, Subtensor{::, ::, ::int64, ::int64}.0)
Toposort index: 183
Inputs types: [TensorType(float32, 4D), TensorType(float32, 4D)]
Inputs shapes: [(1, 64, 1024, 1024), (3, 64, 5, 5)]
Inputs strides: [(268435456, 4194304, 4096, 4), (6400, 100, -20, -4)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Elemwise{Composite{tanh((i0 + i1))}}[(0, 0)](CorrMM{(2, 2), (1, 1)}.0, InplaceDimShuffle{x,0,x,x}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "enhance.py", line 504, in <module>
    enhancer = NeuralEnhancer()
  File "enhance.py", line 427, in __init__
    self.model = Model()
  File "enhance.py", line 232, in __init__
    self.compile()
  File "enhance.py", line 384, in compile
    output = lasagne.layers.get_output([self.network[k] for k in ['img', 'seed', 'out']], input_layers, deterministic=True)
  File "/home/jan/neural-enhance/pyvenv/lib/python3.5/site-packages/lasagne/layers/helper.py", line 191, in get_output
    all_outputs[layer] = layer.get_output_for(layer_inputs, **kwargs)
  File "/home/jan/neural-enhance/pyvenv/lib/python3.5/site-packages/lasagne/layers/conv.py", line 330, in get_output_for
    conved = self.convolve(input, **kwargs)
  File "/home/jan/neural-enhance/pyvenv/lib/python3.5/site-packages/lasagne/layers/conv.py", line 608, in convolve
    filter_flip=self.flip_filters)

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

**Comment by XPanniX** [comment]
Nevermind, didn't see issue #6
