### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by Jinkeycode** [alexjc/neural-enhance#142]
When I run python3 enhance.py --type=photo --model=repair --zoom=1 broken.jpg 。 I got this error， while I have downloaded the pre-trained neural network.

Traceback (most recent call last):
  File "enhance.py", line 581, in <module>
    enhancer = NeuralEnhancer(loader=False)
  File "enhance.py", line 466, in __init__
    self.model = Model()
  File "enhance.py", line 256, in __init__
    config, params = self.load_model()
ValueError: too many values to unpack (expected 2)

**Comment by abhi-kumar** [comment]
Same error encountered. Did you find the solution?

**Comment by Jinkeycode** [comment]
@abhi-kumar don't download the model using link in readme.md. Download it from release.

**Comment by abhi-kumar** [comment]
Thanks.
