### ISSUE TITLE
ValueError: could not broadcast input array from shape (3,185,192) into shape (3,192,192)

### ISSUE THREAD

**Issue by EmailsGmails** [alexjc/neural-enhance#147]
Any idea how this could happen?

Epoch #168 at 21758.8s, lr=2.50e-05
  - generator total=3.57e+02 prcpt=3.17e+02 smthn=1.63e+01 advrs=2.30e+01
  - discriminator 0.964512 15 -0.964511 15
↑↑↓↑↓↑Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "enhance.py", line 222, in run
    self.enqueue(orig, seed)
  File "enhance.py", line 239, in enqueue
    self.orig_buffer[i] = np.transpose(orig_chunk.astype(np.float32) / 255.0 - 0.5, (2, 0, 1))
ValueError: could not broadcast input array from shape (3,185,192) into shape (3,192,192)

↓↓

It suddenly changed image height from 192 to 185? Why? And why at Epoch 168? (Several hours into training).

Can I also keep training this same model immidiately from Epoch 169 if I try again? To not waste time on random errors like this.

**Comment by jacktive** [comment]
Version 0.4 may have some problem, you can use version 0.3. I can not find where's the problem in version 0.4. 

One epoch in this script will not use all images ,it only <code>use args.epochs</code> * <code>args.epoch_size</code>. So the erro happend at Epoch 168 is random.
You run the script with  same args and <strong>do not run</strong> <code>rm -f ne?x*.pkl.bz2</code>,the script will load the model which saved at Epoch 160.

Is that right? @alexjc
