### ISSUE TITLE
Permission denied.

### ISSUE THREAD

**Issue by joshuagordondba** [alexjc/neural-enhance#152]
I get the error permission denied. You can see it picks up the images as it has picked up the 1 image. Permissions set to 777. 

docker run --volume=$(pwd)/input:/ne/input -it alexjc/neural-enhance --zoom=4 --model=default input/*.jpg
_ _
_ __ ___ _ _ _ __ __ | | ___ _ __ | |_ __ _ _ __ ___ ___
| '_ \ / _ \ | | | '__/ | | / _ \ '_ \| '_ \ / _ | ' \ / / _ \
| | | | / || | | | (| | | | / | | | | | | (| | | | | (| /
|| ||_|_,|| _,|| _|| ||| ||_,|| ||__|

Super Resolution for images and videos powered by Deep Learning!

Code licensed as AGPLv3, models under CC BY-NC-SA.
Using the device cpu for neural computation.
Enhancing 1 image(s) specified on the command-line.

Loaded file ne4x-photo-default-0.3.pkl.bz2 with trained model.
input/image.jpg Traceback (most recent call last):
File "enhance.py", line 583, in 
img = scipy.ndimage.imread(filename, mode='RGB')
File "/opt/conda/lib/python3.5/site-packages/scipy/ndimage/io.py", line 24, in imread
return _imread(fname, flatten, mode)
File "/opt/conda/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 154, in imread
im = Image.open(name)
File "/opt/conda/lib/python3.5/site-packages/PIL/Image.py", line 2282, in open
fp = builtins.open(filename, "rb")
PermissionError: [Errno 13] Permission denied: 'input/image.jpg'

If I run this docker run -v $(pwd)/images:/ne/input --entrypoint /bin/bash -it alexjc/neural-enhance
The input folder is not accessible. ls input/ permission denied.
Any Ideas?

**Comment by neighthan** [comment]
I'm also getting `PermissionError`s when trying to use the alias recommended in the README
