### ISSUE TITLE
Use without alias

### ISSUE THREAD

**Issue by SergioMendes93** [alexjc/neural-enhance#156]
Hello, in advance congratulations on the great job!

Is it possible to use without the alias? I'm trying to use like this:
docker run --rm -v `pwd`:/ne/input -it alexjc/neural-enhance --zoom=2 macos.jpg
 
And I get the following output even though i'm on the current directory of the jpg

macos.jpg Traceback (most recent call last):
  File "enhance.py", line 583, in <module>
    img = scipy.ndimage.imread(filename, mode='RGB')
  File "/opt/conda/lib/python3.5/site-packages/scipy/ndimage/io.py", line 24, in imread
    return _imread(fname, flatten, mode)
  File "/opt/conda/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/conda/lib/python3.5/site-packages/PIL/Image.py", line 2282, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'macos.jpg'

Thanks!

**Comment by mattfredwill** [comment]
Prefix the filename with the volume location, ie:

`docker run --rm -v pwd:/ne/input -it alexjc/neural-enhance --zoom=2 /ne/input/macos.jpg`

**Comment by JessieW-eyevio** [comment]
no, this still does not solve mu problem
