### ISSUE TITLE
AssertionError: AbstractConv2d Theano optimization failed: there is no implementation available supporting the requested options. Did you exclude both "conv_dnn" and "conv_gemm" fro        m the optimizer? If on GPU, is cuDNN available and does the GPU support it? If on CPU, do you have a BLAS library installed Theano can link against?

### ISSUE THREAD

**Issue by FIGHTFORGLO** [alexjc/neural-enhance#158]
This is my problem:

Traceback (most recent call last):
  File "enhance.py", line 580, in <module>
    enhancer = NeuralEnhancer(loader=False)
  File "enhance.py", line 465, in __init__
    self.model = Model()
  File "enhance.py", line 264, in __init__
    self.compile()
  File "enhance.py", line 422, in compile
    self.predict = theano.function([seed_tensor], output)
  File "/home/pyvenv/lib/python3.5/site-packages/theano/compile/function.py", line 320, in function
    output_keys=output_keys)
  File "/home/pyvenv/lib/python3.5/site-packages/theano/compile/pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "/home/pyvenv/lib/python3.5/site-packages/theano/compile/function_module.py", line 1776, in orig_function
    output_keys=output_keys).create(
  File "/home/pyvenv/lib/python3.5/site-packages/theano/compile/function_module.py", line 1456, in __init__
    optimizer_profile = optimizer(fgraph)
  File "/home/pyvenv/lib/python3.5/site-packages/theano/gof/opt.py", line 101, in __call__
    return self.optimize(fgraph)
  File "/home/pyvenv/lib/python3.5/site-packages/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/pyvenv/lib/python3.5/site-packages/theano/gof/opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/pyvenv/lib/python3.5/site-packages/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/pyvenv/lib/python3.5/site-packages/theano/gof/opt.py", line 1879, in apply
    nb += self.process_node(fgraph, node)
  File "/home/pyvenv/lib/python3.5/site-packages/theano/gof/opt.py", line 1777, in process_node
    lopt, node)
  File "/home/pyvenv/lib/python3.5/site-packages/theano/gof/opt.py", line 1673, in warn_inplace
    return NavigatorOptimizer.warn(exc, nav, repl_pairs, local_opt, node)
  File "/home/pyvenv/lib/python3.5/site-packages/theano/gof/opt.py", line 1659, in warn
    raise exc
  File "/home/pyvenv/lib/python3.5/site-packages/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/home/pyvenv/lib/python3.5/site-packages/theano/tensor/nnet/opt.py", line 402, in local_abstractconv_check
    node.op.__class__.__name__)
AssertionError: AbstractConv2d Theano optimization failed: there is no implementation available supporting the requested options. Did you exclude both "conv_dnn" and "conv_gemm" fro        m the optimizer? If on GPU, is cuDNN available and does the GPU support it? If on CPU, do you have a BLAS library installed Theano can link against?

Can you help me?Thanks.

**Comment by ashtrankov** [comment]
I have the same issue on windows 10

**Comment by JustinhoCHN** [comment]
same problem here, ubuntu16.04, conda envs, already pip installed requirement.txt

**Comment by JustinhoCHN** [comment]
solved , see this : https://github.com/fchollet/keras/issues/2845
> met the same problem and fixed by adding "optimizer = None" in ".theanorc"

**Comment by Roshana-Naqvi** [comment]
where this file ".theanorc" is located ?

**Comment by furkansherwani** [comment]
> where this file ".theanorc" is located ?

Hello Roshana, Did you get the answer?

**Comment by Roshana-Naqvi** [comment]
> > where this file ".theanorc" is located ?
> 
> Hello Roshana, Did you get the answer?

No dear.

**Comment by Roshana-Naqvi** [comment]
> > where this file ".theanorc" is located ?
> 
> Hello Roshana, Did you get the answer?

Which code you are running?

**Comment by furkansherwani** [comment]
> > > where this file ".theanorc" is located ?
> > 
> > 
> > Hello Roshana, Did you get the answer?
> 
> Which code you are running?

I have just tried this and it worked:
https://github.com/keras-team/keras/issues/2845#issuecomment-405707382

By the way I am trying to run:
https://github.com/marcellacornia/mlnet
