### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [alexjc/neural-enhance#176]
Hello there,

I am using the docker installation and If I try to put a correct path to the script

```
enhance --zoom=1 --model=repair /Users/vaevictis/Desktop/\<3.jpg
```

then I get
```

/Users/vaevictis/Desktop/<3.jpg Traceback (most recent call last):
  File "enhance.py", line 583, in <module>
    img = scipy.ndimage.imread(filename, mode='RGB')
  File "/opt/conda/lib/python3.5/site-packages/scipy/ndimage/io.py", line 24, in imread
    return _imread(fname, flatten, mode)
  File "/opt/conda/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/conda/lib/python3.5/site-packages/PIL/Image.py", line 2282, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/vaevictis/Desktop/<3.jpg'

```
Any ideas of what could be the problem?

Cheers,

Francesco Saverio

**Comment by Zorgatone** [comment]
Same problem here

**Comment by geraldoramos** [comment]
+1

**Comment by exussum12** [comment]
This issue is you are mapping to docker.

Try using the helper command given

     alias enhance='function ne() { docker run --rm -v "$(pwd)/`dirname ${@:$#}`":/ne/input -it alexjc/neural-enhance ${@:1:$#-1} "input/`basename ${@:$#}`"; }; ne'


After that has been run, You should be able to cd to the directory and enchance the file

Docker is a container so the path mappings are differnt between your pc and the container

**Comment by lquessenberry** [comment]
I ran the alias and I am still getting this error.

**Comment by exussum12** [comment]
Try being in that directory.

eg enhance image.jpg

No other path.
Its likely a mismatch between the docker container paths and your actual system paths

**Comment by post2web** [comment]
same here

**Comment by exussum12** [comment]
Post the command you are using. It's very likely the command you are using is not friendly to docker mappings

**Comment by post2web** [comment]
I am using the command that creates alias from the documentation:
```
alias enhance='function ne() { docker run --rm -v "$(pwd)/`dirname ${@:$#}`":/ne/input -it alexjc/neural-enhance ${@:1:$#-1} "input/`basename ${@:$#}`"; }; ne'
```
Then when I try to execute it:
```
~: enhance --zoom=1 --model=repair images/input_image.jpg
                             _              _
  _ __   ___ _   _ _ __ __ _| |   ___ _ __ | |__   __ _ _ __   ___ ___
 | '_ \ / _ \ | | | '__/ _` | |  / _ \ '_ \| '_ \ / _` | '_ \ / __/ _ \
 | | | |  __/ |_| | | | (_| | | |  __/ | | | | | | (_| | | | | (_|  __/
 |_| |_|\___|\__,_|_|  \__,_|_|  \___|_| |_|_| |_|\__,_|_| |_|\___\___|

Super Resolution for images and videos powered by Deep Learning!
  - Code licensed as AGPLv3, models under CC BY-NC-SA.
  - Using the device `cpu` for neural computation.

Enhancing 2 image(s) specified on the command-line.
  - Loaded file `ne1x-photo-repair-0.3.pkl.bz2` with trained model.

images/input_image.jpg Traceback (most recent call last):
  File "enhance.py", line 583, in <module>
    img = scipy.ndimage.imread(filename, mode='RGB')
  File "/opt/conda/lib/python3.5/site-packages/scipy/ndimage/io.py", line 24, in imread
    return _imread(fname, flatten, mode)
  File "/opt/conda/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/conda/lib/python3.5/site-packages/PIL/Image.py", line 2282, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'images/input_image.jpg'
~:
```

**Comment by exussum12** [comment]
Either be in the directory (so it's just input_image.jpg) or quote the path

**Comment by post2web** [comment]
I tried with a quoted path and with just input_image.jpg without a directory.
```
~: enhance --zoom=1 --model=repair input_image.jpg
                             _              _
  _ __   ___ _   _ _ __ __ _| |   ___ _ __ | |__   __ _ _ __   ___ ___
 | '_ \ / _ \ | | | '__/ _` | |  / _ \ '_ \| '_ \ / _` | '_ \ / __/ _ \
 | | | |  __/ |_| | | | (_| | | |  __/ | | | | | | (_| | | | | (_|  __/
 |_| |_|\___|\__,_|_|  \__,_|_|  \___|_| |_|_| |_|\__,_|_| |_|\___\___|

Super Resolution for images and videos powered by Deep Learning!
  - Code licensed as AGPLv3, models under CC BY-NC-SA.
  - Using the device `cpu` for neural computation.

Enhancing 2 image(s) specified on the command-line.
  - Loaded file `ne1x-photo-repair-0.3.pkl.bz2` with trained model.

input_image.jpg Traceback (most recent call last):
  File "enhance.py", line 583, in <module>
    img = scipy.ndimage.imread(filename, mode='RGB')
  File "/opt/conda/lib/python3.5/site-packages/scipy/ndimage/io.py", line 24, in imread
    return _imread(fname, flatten, mode)
  File "/opt/conda/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/conda/lib/python3.5/site-packages/PIL/Image.py", line 2282, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'input_image.jpg'
```
And get the same output for:
```
enhance --zoom=1 --model=repair "input_image.jpg"
```
Afcours, there is a file input_image.jpg in my current dir:
```
~: ls input_image.jpg
input_image.jpg
```

**Comment by meaninglessLives** [comment]
The following procedure worked for me in windows 8.1. 
Create alias as suggested in the documentation `(alias enhance='function ne() ....)`.
create a directory called images in C:/Users/your_user_name/
 type `cd images` . (By default you are already in C:/Users/your_user_name/ directory)
Now just type `'enhance your_image_name.jpg'` and it should work.
But I am still unable to cd to any random directory and use enhance. I get `FileNotFoundError: [Errno 2] No such file or directory:`
Note- In my understanding you have to create alias every time you open docker or you can put it in a bash file.

**Comment by hugheba** [comment]
same problem here on Mac OS 10.13.1.

**Comment by sleeepyjack** [comment]
Switching from zsh to bash resolved the problem for me.

**Comment by maluramichael** [comment]
@sleeepyjack this is working for me too.

**Comment by Zorgatone** [comment]
Yeah looks like the issue was zsh for me as well. Working now with bash

**Comment by z** [comment]
Instead of passing the expansion pattern to the container:

```
docker run --rm -v $(pwd):/ne/input -it alexjc/neural-enhance --type=photo --zoom=2 "images/*.jpg"
```

Try enumerating a list of files on the "host" first, adding an absolute path prefix to each file, `/ne/input/`. 
 Then pass the one long list of filenames as the parameter to the python script running in the container:

```
docker run --rm -v $(pwd):/ne/input -it alexjc/neural-enhance --type=photo --zoom=2 $(find images -iname "*.jpg" | sed "s#^\./##")
```

**Comment by whyboris** [comment]
Spent about an hour trying out different combinations of folders, locations, etc. Turns out it was a problem with `zsh`. Switch to `bash` and it's done. Switching is [easy](https://stackoverflow.com/a/10341338/5017391), just run:
`exec bash`
and when you want zsh back, just 
`exec zsh`

Current _README_ instructions are enough to succeed, place this in `.bashrc`:
`alias enhance='function ne() { docker run --rm -v "$(pwd)/`dirname ${@:$#}`":/ne/input -it alexjc/neural-enhance ${@:1:$#-1} "input/`basename ${@:$#}`"; }; ne'`

Now go to the directory with your image (e.g. _0.jpg_) and execute this:
`enhance --zoom=1 --model=repair 0.jpg`
You'll get a `0_ne1x.jpg` output in the same directory <3

**Comment by MatheusRV** [comment]
@whyboris this comand isn't working on Ubuntu Windows Subsystem - WSL

**Comment by FrancescoSaverioZuppichini** [comment]
@whyboris Thank you, that solved the issue!

**Comment by FrancescoSaverioZuppichini** [comment]
Getting same error on Ubuntu 18.04 even by running

```
chsh -s /bin/bash
```
to use bash and not myzsh

**Comment by benwinding** [comment]
Can anyone get this working in `zsh`?
