### ISSUE TITLE
Adding vgg19 model to docker fails

### ISSUE THREAD

**Issue by ipaterson89** [alexjc/neural-enhance#177]
Hi

Thanks for providing the tool. I'm trying to add the vgg19 model to the docker image. 

After wget'ing the image file to local directory, I created a Dockerfile with the following: 

>FROM alexjc/neural-enhance
>COPY ne1x-photo-vgg19-0.3.pkl.bz2 .

From there, executed the build:
`docker build .`

It built fine. 

After aliasing the enhance command per the docs, I ran the following command: 

`enhance --zoom=1 --model=vgg19 z.jpg;`

It returned the following errors: 

>MBA-ONE:Docker $ enhance --zoom=1 --model=vgg19 z.jpg;
>                             _              _
>  _ __   ___ _   _ _ __ __ _| |   ___ _ __ | |__   __ _ _ __   ___ ___
> | '_ \ / _ \ | | | '__/ _` | |  / _ \ '_ \| '_ \ / _` | '_ \ / __/ _ \
> | | | |  __/ |_| | | | (_| | | |  __/ | | | | | | (_| | | | | (_|  __/
> |_| |_|\___|\__,_|_|  \__,_|_|  \___|_| |_|_| |_|\__,_|_| |_|\___\___|
>
>Super Resolution for images and videos powered by Deep Learning!
>  - Code licensed as AGPLv3, models under CC BY-NC-SA.
>  - Using the device `cpu` for neural computation.
>
>Enhancing 1 image(s) specified on the command-line.
>  - Loaded file `ne1x-photo-vgg19-0.3.pkl.bz2` with trained model.
>Traceback (most recent call last):
>  File "enhance.py", line 580, in <module>
>    enhancer = NeuralEnhancer(loader=False)
>  File "enhance.py", line 465, in __init__
>    self.model = Model()
>  File "enhance.py", line 255, in __init__
>    config, params = self.load_model()
>ValueError: too many values to unpack (expected 2)
>MBA-ONE:Docker $

Any suggestions on the correct way to add the vgg19 library?

**Comment by rongyuer** [comment]
I had the same peoblem,
I down the vgg model named vgg19_conv.pkl.bz2 are not ne1x-photo-vgg19-0.3.pkl.bz2，so I renamed 
vgg19_conv.pkl.bz2 with vgg19_conv.pkl.bz2，but like blow problem。by the way I also use docker to test this tool。 
i cannot slove this problem like this ：
Loaded file ne1x-photo-vgg19-0.3.pkl.bz2 with trained model.
Traceback (most recent call last):
File "enhance.py", line 580, in 
enhancer = NeuralEnhancer(loader=False)
File "enhance.py", line 465, in init
self.model = Model()
File "enhance.py", line 255, in init
config, params = self.load_model()
ValueError: too many values to unpack (expected 2)
