### ISSUE TITLE
ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.7 or higher required) NoneType

### ISSUE THREAD

**Issue by shede1988** [alexjc/neural-enhance#185]
ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.7 or higher required)
NoneType

**Comment by Hunterwolf88** [comment]
similar here
`Message: 'error("pygpu was configured but could not be imported", exc_info=True)`

**Comment by kenken64** [comment]
_              _
  _ __   ___ _   _ _ __ __ _| |   ___ _ __ | |__   __ _ _ __   ___ ___
 | '_ \ / _ \ | | | '__/ _` | |  / _ \ '_ \| '_ \ / _` | '_ \ / __/ _ \
 | | | |  __/ |_| | | | (_| | | |  __/ | | | | | | (_| | | | | (_|  __/
 |_| |_|\___|\__,_|_|  \__,_|_|  \___|_| |_|_| |_|\__,_|_| |_|\___\___|

Super Resolution for images and videos powered by Deep Learning!
  - Code licensed as AGPLv3, models under CC BY-NC-SA.
ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.7 or higher required)
NoneType: None
Traceback (most recent call last):
  File "enhance.py", line 125, in <module>
    import lasagne
  File "/home/issadmin/.virtualenvs/dl4cv/lib/python3.6/site-packages/lasagne/__init__.py", line 19, in <module>
    from . import layers
  File "/home/issadmin/.virtualenvs/dl4cv/lib/python3.6/site-packages/lasagne/layers/__init__.py", line 7, in <module>
    from .pool import *
  File "/home/issadmin/.virtualenvs/dl4cv/lib/python3.6/site-packages/lasagne/layers/pool.py", line 6, in <module>
    from theano.tensor.signal import downsample
ImportError: cannot import name 'downsample'

**Comment by olaviinha** [comment]
A tad late to the party but I guess it's time for 2020 update. The following resolves the PyGPU issue.

Downgrade cuda:
```
  wget https://developer.nvidia.com/compute/cuda/8.0/Prod2/local_installers/cuda-repo-ubuntu1604-8-0-local-ga2_8.0.61-1_amd64-deb
  dpkg -i cuda-repo-ubuntu1604-8-0-local-ga2_8.0.61-1_amd64-deb
  apt-get update
  apt-get install cuda=8.0.61-1 libopenblas-dev
```

Install libgpuarray/pygpu
```
  git clone https://github.com/Theano/libgpuarray.git
  cd /content/libgpuarray/
  mkdir Build
  cd Build
  cmake .. -DCMAKE_BUILD_TYPE=Release
  make
  make install
  cd ..
  python setup.py build
  python setup.py install
```
