### ISSUE TITLE
Theano raises initialization error in GPU use 

### ISSUE THREAD

**Issue by erogol** [alexjc/neural-enhance#19]
I've follow everything suggested for Linux setup. It works fine for CPU but when I switch to GPU I got this error;

```
ERROR (theano.sandbox.cuda): ERROR: Not using GPU. Initialisation of device gpu failed:
initCnmem: cnmemInit call failed! Reason=CNMEM_STATUS_OUT_OF_MEMORY. numdev=1

Traceback (most recent call last):
  File "enhance.py", line 106, in <module>
    import theano
  File "/media/eightbit/data_hdd/Libs/Python/neural-enhance/pyvenv/lib/python3.4/site-packages/theano/__init__.py", line 103, in <module>
    import theano.sandbox.cuda
  File "/media/eightbit/data_hdd/Libs/Python/neural-enhance/pyvenv/lib/python3.4/site-packages/theano/sandbox/cuda/__init__.py", line 697, in <module>
    use(device=config.device, force=config.force_device, test_driver=False)
  File "/media/eightbit/data_hdd/Libs/Python/neural-enhance/pyvenv/lib/python3.4/site-packages/theano/sandbox/cuda/__init__.py", line 557, in use
    gpu_init(use.device_number, config.lib.cnmem)
RuntimeError: ('initCnmem: cnmemInit call failed! Reason=CNMEM_STATUS_OUT_OF_MEMORY. numdev=1\n', 'You asked to force this device and it failed. No fallback to the cpu or other gpu device.')
```

Do I need to point my GPU for this pyvenv  stuff in the project? Or any other idea for a solution ?

**Comment by alexjc** [comment]
Try editing `cnnmem` variable in the script on this line, set it to 0.9 or just remove it completely:
https://github.com/alexjc/neural-enhance/blob/master/enhance.py#L99

Let me know if that works. If it does, PR for setting it to 0.9 is welcome!
