### ISSUE TITLE
Could not load image for training? too small? how to bypass? 

### ISSUE THREAD

**Issue by elhoussinetalab** [alexjc/neural-enhance#195]
Hi, I tried to train with this command: 
`python3 enhance.py --train "/my/path/to/dataset/*.jpg" --model custom --zoom=2 --epochs=50 --perceptual-layer=conv2_2 --smoothness-weight=1e7 --adversary-weight=0.0 --generator-blocks=4 --generator-filters=64 --device=gpu`

and I keep on getting this error for all the images in my dataset: 

`WARNING: Could not load `/my/path/to/dataset/some_image.jpg` as image.
  - Try fixing or removing the file before next run.`

It turns out that the image is too small, any idea on how to bypass this? thank you.

**Comment by elhoussinetalab** [comment]
and when I ignore the warning, it ends up with this error: 

`Traceback (most recent call last):
  File "enhance.py", line 577, in <module>
    enhancer = NeuralEnhancer(loader=True)
  File "enhance.py", line 465, in __init__
    self.model = Model()
  File "enhance.py", line 264, in __init__
    self.compile()
  File "enhance.py", line 422, in compile
    self.predict = theano.function([seed_tensor], output)
  File "/usr/local/lib/python3.5/dist-packages/theano/compile/function.py", line 320, in function
    output_keys=output_keys)
  File "/usr/local/lib/python3.5/dist-packages/theano/compile/pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "/usr/local/lib/python3.5/dist-packages/theano/compile/function_module.py", line 1777, in orig_function
    defaults)
  File "/usr/local/lib/python3.5/dist-packages/theano/compile/function_module.py", line 1641, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/usr/local/lib/python3.5/dist-packages/theano/gof/link.py", line 690, in make_thunk`

`Exception: ('The following error happened while compiling the node', GpuDnnConv{algo='small', inplace=True}(GpuContiguous.0, GpuContiguous.0, GpuAllocEmpty.0, GpuDnnConvDesc{border_mode=(3, 3), subsample=(1, 1), conv_mode='conv', precision='float32'}.0, Constant{1.0}, Constant{0.0}), '\n', 'nvcc return status', 2, 'for cmd', 'nvcc -shared -O3 -Xlinker -rpath,/usr/local/cuda-8.0/lib64 -arch=sm_37 -m64 -Xcompiler -fno-math-errno,-Wno-unused-label,-Wno-unused-variable,-Wno-write-strings,-D_FORCE_INLINES,-DCUDA_NDARRAY_CUH=mc72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden -Xlinker -rpath,/root/.theano/compiledir_Linux-4.4--aws-x86_64-with-Ubuntu-16.04-xenial-x86_64-3.5.2-64/cuda_ndarray -I/root/.theano/compiledir_Linux-4.4--aws-x86_64-with-Ubuntu-16.04-xenial-x86_64-3.5.2-64/cuda_ndarray -I/usr/local/cuda-8.0/include -I/usr/local/lib/python3.5/dist-packages/theano/sandbox/cuda -I/usr/local/lib/python3.5/dist-packages/numpy/core/include -I/usr/include/python3.5m -I/usr/local/lib/python3.5/dist-packages/theano/gof -o /root/.theano/compiledir_Linux-4.4--aws-x86_64-with-Ubuntu-16.04-xenial-x86_64-3.5.2-64/tmp2ex9ntsd/m1b4b87b9831a7c1022a8899fd1be603f.so mod.cu -L/root/.theano/compiledir_Linux-4.4--aws-x86_64-with-Ubuntu-16.04-xenial-x86_64-3.5.2-64/cuda_ndarray -L/usr/lib -lcudart -lcublas -lcuda_ndarray -lcudnn -lpython3.5m', "[GpuDnnConv{algo='small', inplace=True}(<CudaNdarrayType(float32, 4D)>, <CudaNdarrayType(float32, 4D)>, <CudaNdarrayType(float32, 4D)>, <CDataType{cudnnConvolutionDescriptor_t}>, Constant{1.0}, Constant{0.0})]")
`
