### ISSUE TITLE
UnicodeEncodeError on Docker when when training

### ISSUE THREAD

**Issue by elonen** [alexjc/neural-enhance#199]
When running...

`/opt/conda/bin/python3.5 enhance.py --train "$OPEN_IMAGES_PATH/*.jpg" --type photo --model default --epochs=50 --batch-shape=256 --generator-downscale=0 --generator-upscale=1     --generator-blocks=8 --generator-filters=128 --generator-residual=0 --perceptual-layer=conv2_2 --smoothness-weight=1e7 --adversary-weight=0.0 --train-noise=1.0`

...on the current Docker image, I got:

`
Traceback (most recent call last):
  File "enhance.py", line 578, in <module>
    enhancer.train()
  File "enhance.py", line 509, in train
    print('\u2191' if l > average else '\u2193', end='', flush=True)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2193' in position 0: ordinal not in range(128)
`

Perhaps the image needs Locales installed or something?

**Comment by xiangzhai** [comment]
Workaround:

```
diff --git a/enhance.py b/enhance.py
index becb851..d4b4c10 100755
--- a/enhance.py
+++ b/enhance.py
@@ -1,3 +1,4 @@
+# -*- coding: utf-8 -*-
 #!/usr/bin/env python3
 """                          _              _                           
   _ __   ___ _   _ _ __ __ _| |   ___ _ __ | |__   __ _ _ __   ___ ___  
@@ -506,7 +507,7 @@ class NeuralEnhancer(object):
                     l = np.sum(losses)
                     assert not np.isnan(losses).any()
                     average = l if average is None else average * 0.95 + 0.05 * l
-                    print('↑' if l > average else '↓', end='', flush=True)
+                    print('^' if l > average else 'v', end='', flush=True)
 
                 scald, repro = self.model.predict(seeds)
                 self.show_progress(images, scald, repro)
```
