### ISSUE TITLE
Dockerfiles don't build like Docker hub's image

### ISSUE THREAD

**Issue by ddmng** [alexjc/neural-enhance#20]
If I use the dockerfile (for cpu) in the the sources, the containers don't work like using your docker hub's image. Here's what I get:

```
docker run -ti --rm -v /images:/ne/images enhance 
Traceback (most recent call last):
  File "enhance.py", line 40, in <module>
    add_arg('--model',              default='small', type=str,          help='Name of the neural network to load/save.')
  File "/opt/conda/lib/python3.5/argparse.py", line 1344, in add_argument
    return self._add_action(action)
  File "/opt/conda/lib/python3.5/argparse.py", line 1707, in _add_action
    self._optionals._add_action(action)
  File "/opt/conda/lib/python3.5/argparse.py", line 1548, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/opt/conda/lib/python3.5/argparse.py", line 1358, in _add_action
    self._check_conflict(action)
  File "/opt/conda/lib/python3.5/argparse.py", line 1497, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/opt/conda/lib/python3.5/argparse.py", line 1506, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --model: conflicting option string: --model
```

It seems that github's sources are different from those you are using to build the image.

**Comment by xuyifeng-nwpu** [comment]
You can see the website :dockerhub.

**Comment by ddmng** [comment]
Pulling latest sources this morning solves the problem.
