### ISSUE TITLE
any solution for this issue please 

### ISSUE THREAD

**Issue by sosinfo212** [alexjc/neural-enhance#207]
i got this error when i execute **" enhance --zoom=1 --model=repair 1.jpg "**

```
Super Resolution for images and videos powered by Deep Learning!
  - Code licensed as AGPLv3, models under CC BY-NC-SA.
  - Using the device `cpu` for neural computation.

Enhancing 2 image(s) specified on the command-line.
  - Loaded file `ne1x-photo-repair-0.3.pkl.bz2` with trained model.

1.jpg Traceback (most recent call last):
  File "enhance.py", line 583, in <module>
    img = scipy.ndimage.imread(filename, mode='RGB')
  File "/opt/conda/lib/python3.5/site-packages/scipy/ndimage/io.py", line 24, in imread
    return _imread(fname, flatten, mode)
  File "/opt/conda/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/conda/lib/python3.5/site-packages/PIL/Image.py", line 2282, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '1.jpg'
```

**Comment by sosinfo212** [comment]
yes i put this img in all directories hahaha which  Directory should i put it inside ?

**Comment by wildeyevr** [comment]
should work... with your command it needs to be in the root dir where the enhance.py script is... also be sure that the image is indeed a .jpg... the extension may be .jpeg or it could be a a different file type with the wrong extension... try opening that image in paint or something and save it as a new file... like "test_1.jpg"... then run the command enhance --zoom=1 --model=repair "test_1.jpg"

/r
