### ISSUE TITLE
issue with passing arguments using docker

### ISSUE THREAD

**Issue by sammcj** [alexjc/neural-enhance#219]
- Docker 18.09.2 (macOS)
- The same issue using ZSH or Bash for the alias

When using the alias:

```
enhance --type=photo --model=repair --zoom=2 orig.jpg
```

Error:

```
  _ __   ___ _   _ _ __ __ _| |   ___ _ __ | |__   __ _ _ __   ___ ___
 | '_ \ / _ \ | | | '__/ _` | |  / _ \ '_ \| '_ \ / _` | '_ \ / __/ _ \
 | | | |  __/ |_| | | | (_| | | |  __/ | | | | | | (_| | | | | (_|  __/
 |_| |_|\___|\__,_|_|  \__,_|_|  \___|_| |_|_| |_|\__,_|_| |_|\___\___|

Super Resolution for images and videos powered by Deep Learning!
  - Code licensed as AGPLv3, models under CC BY-NC-SA.
ERROR (theano.sandbox.gpuarray): pygpu was configured but could not be imported
NoneType
  - Using the device `opencl` for neural computation.

Enhancing 1 image(s) specified on the command-line.
  - Loaded file `ne2x-photo-default-0.3.pkl.bz2` with trained model.

/ne/input/--type=photo Traceback (most recent call last):
  File "enhance.py", line 583, in <module>
    img = scipy.ndimage.imread(filename, mode='RGB')
  File "/opt/conda/lib/python3.5/site-packages/scipy/ndimage/io.py", line 24, in imread
    return _imread(fname, flatten, mode)
  File "/opt/conda/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/conda/lib/python3.5/site-packages/PIL/Image.py", line 2282, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/ne/input/--type=photo'
```

When calling Docker directly:

```
docker run --rm -v `pwd`:/ne/input -it alexjc/neural-enhance --type=photo --model=repair --zoom=2 orig.jpg
```

Error:

```
  _ __   ___ _   _ _ __ __ _| |   ___ _ __ | |__   __ _ _ __   ___ ___
 | '_ \ / _ \ | | | '__/ _` | |  / _ \ '_ \| '_ \ / _` | '_ \ / __/ _ \
 | | | |  __/ |_| | | | (_| | | |  __/ | | | | | | (_| | | | | (_|  __/
 |_| |_|\___|\__,_|_|  \__,_|_|  \___|_| |_|_| |_|\__,_|_| |_|\___\___|

Super Resolution for images and videos powered by Deep Learning!
  - Code licensed as AGPLv3, models under CC BY-NC-SA.
  - Using the device `cpu` for neural computation.

Enhancing 1 image(s) specified on the command-line.

ERROR: Model file with pre-trained convolution layers not found. Download it here...
https://github.com/alexjc/neural-enhance/releases/download/v0.3/ne2x-photo-repair-0.3.pkl.bz2
```

**Comment by mvrozanti** [comment]
That's okay... The instructions under the last output you posted is explicit: the pre-trained model needs to be downloaded, unless you wanna train your own network. 

The problem is, that URL returns 404.

**Comment by sammcj** [comment]
Oh right, I would have expected the first docket run to have done this, I should have checked the dockerfile.
