### ISSUE TITLE
you need scipy==0.19.1, not the most recent version, which removed "fromimage"

### ISSUE THREAD

**Issue by rudluff** [alexjc/neural-enhance#223]
with most recent scipy, which deprecated 'fromimage', it will only train 1 epoch and then hang here infinitely which is lame:

`Training 50 epochs on random image sections with batch size 30.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "enhance.py", line 161, in run
    self.add_to_buffer(f)
  File "enhance.py", line 188, in add_to_buffer
    orig = scipy.misc.fromimage(orig).astype(np.float32)
AttributeError: module 'scipy.misc' has no attribute 'fromimage'

Training 50 epochs on random image sections with batch size 30.
  - 23 tensors learned for generator.
  - 21 tensors learned for discriminator.
`

solution, for all the kiddies at home:
`python3 -m pip install scipy==0.19.1`

**Comment by laptopsftw** [comment]
use `np.asarray` instead, as per SciPy Documentation

**Comment by laptopsftw** [comment]
> with most recent scipy, which deprecated 'fromimage', it will only train 1 epoch and then hang here infinitely which is lame:
> 
> `Training 50 epochs on random image sections with batch size 30.
> Exception in thread Thread-1:
> Traceback (most recent call last):
> File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
> self.run()
> File "enhance.py", line 161, in run
> self.add_to_buffer(f)
> File "enhance.py", line 188, in add_to_buffer
> orig = scipy.misc.fromimage(orig).astype(np.float32)
> AttributeError: module 'scipy.misc' has no attribute 'fromimage'
> 
> Training 50 epochs on random image sections with batch size 30.
> 
>     * 23 tensors learned for generator.
> 
>     * 21 tensors learned for discriminator.
>       `
> 
> 
> solution, for all the kiddies at home:
> `python3 -m pip install scipy==0.19.1`

tried 1.1.0. depreciated, not removed. does it worked?

**Comment by pahanini** [comment]
Downgrading scipy works for me:
```
pip uninstall scipy
pip install scipy==1.1.0
 ```
