### ISSUE TITLE
Running on windows

### ISSUE THREAD

**Issue by mcDandy** [alexjc/neural-enhance#230]
I installed all needed dependencies. I use 64 bit python. Windows 10 PowerShell
What I need to do? 

Super Resolution for images and videos powered by Deep Learning![0;36m
  - Code licensed as AGPLv3, models under CC BY-NC-SA.[0m
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Traceback (most recent call last):
  File ".\enhance.py", line 125, in <module>
    import lasagne
  File "C:\Program Files\Python37\lib\site-packages\lasagne\__init__.py", line 19, in <module>
    from . import layers
  File "C:\Program Files\Python37\lib\site-packages\lasagne\layers\__init__.py", line 7, in <module>
    from .pool import *
  File "C:\Program Files\Python37\lib\site-packages\lasagne\layers\pool.py", line 6, in <module>
    from theano.tensor.signal import downsample
ImportError: cannot import name 'downsample' from 'theano.tensor.signal' (C:\Program Files\Python37\lib\site-packages\theano\tensor\signal\__init__.py)

**Comment by dan-r95** [comment]
Maybe [this](https://github.com/aigamedev/scikit-neuralnetwork/issues/235) helps.
Edit the `requirements.txt` file to install `theano==0.7`.

**Comment by DreamRT** [comment]
installing Theano==0.8.2 will be okay
