### ISSUE TITLE
Enhance getting file not found issue.

### ISSUE THREAD

**Issue by NarasimmanSaravana1994** [alexjc/neural-enhance#233]
Given cmd :
**sudo docker run -i -t alexjc/neural-enhance --zoom=1 --model=repair /media/administrator/hdd/Licese_plate_RND/test.jpg**

Error:

                             _              _                           
  _ __   ___ _   _ _ __ __ _| |   ___ _ __ | |__   __ _ _ __   ___ ___  
 | '_ \ / _ \ | | | '__/ _` | |  / _ \ '_ \| '_ \ / _` | '_ \ / __/ _ \ 
 | | | |  __/ |_| | | | (_| | | |  __/ | | | | | | (_| | | | | (_|  __/ 
 |_| |_|\___|\__,_|_|  \__,_|_|  \___|_| |_|_| |_|\__,_|_| |_|\___\___| 

Super Resolution for images and videos powered by Deep Learning!
  - Code licensed as AGPLv3, models under CC BY-NC-SA.
  - Using the device `cpu` for neural computation.

Enhancing 1 image(s) specified on the command-line.
  - Loaded file `ne1x-photo-repair-0.3.pkl.bz2` with trained model.

/media/administrator/hdd/Licese_plate_RND/test.jpg Traceback (most recent call last):
  File "enhance.py", line 583, in <module>
    img = scipy.ndimage.imread(filename, mode='RGB')
  File "/opt/conda/lib/python3.5/site-packages/scipy/ndimage/io.py", line 24, in imread
    return _imread(fname, flatten, mode)
  File "/opt/conda/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/conda/lib/python3.5/site-packages/PIL/Image.py", line 2282, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/media/administrator/hdd/Licese_plate_RND/test.jpg'
(license_test) administrator@administrator-System-Product-Name:/media/administrator/hdd/Licese_plate_RND$

**Comment by abougouffa** [comment]
I have the same problem, any help?!
