### ISSUE TITLE
AssertionError: AbstractConv2d Theano optimization failed

### ISSUE THREAD

**Issue by Entretoize** [alexjc/neural-enhance#252]
I'm trying to make it work on windows but it doesn't, I used the manual installation, i did:

`python3 -m venv pyvenv --system-site-packages`
`python3 -m pip install --ignore-installed -r requirements.txt`
I downloaded the release and put it in C:\Program Files\Neuralenhance with BLAS.
But the result is : 

C:\Program Files\Neuralenhance>enhance.py --zoom=2 --model=repair 0.jpg
[1;36m                             _              _
  _ __   ___ _   _ _ __ __ _| |   ___ _ __ | |__   __ _ _ __   ___ ___
 | '_ \ / _ \ | | | '__/ _` | |  / _ \ '_ \| '_ \ / _` | '_ \ / __/ _ \
 | | | |  __/ |_| | | | (_| | | |  __/ | | | | | | (_| | | | | (_|  __/
 |_| |_|\___|\__,_|_|  \__,_|_|  \___|_| |_|_| |_|\__,_|_| |_|\___\___|

Super Resolution for images and videos powered by Deep Learning![0;36m
  - Code licensed as AGPLv3, models under CC BY-NC-SA.[0m
[0;36m  - Using the device `cpu` for neural computation.[0m

[1;94mEnhancing 1 image(s) specified on the command-line.[0;94m
  - Loaded file `ne2x-photo-repair-0.3.pkl.bz2` with trained model.
ERROR (theano.gof.opt): Optimization failure due to: local_abstractconv_check
ERROR (theano.gof.opt): node: AbstractConv2d{border_mode=(3, 3), subsample=(1, 1), filter_flip=True, imshp=(None, 3, None, None), kshp=(128, 3, 7, 7)}(<TensorType(float32, 4D)>, W)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\theano\gof\opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "C:\ProgramData\Miniconda3\lib\site-packages\theano\tensor\nnet\opt.py", line 396, in local_abstractconv_check
    raise AssertionError(
AssertionError: AbstractConv2d Theano optimization failed: there is no implementation available supporting the requested options. Did you exclude both "conv_dnn" and "conv_gemm" from the optimizer? If on GPU, is cuDNN available and does the GPU support it? If on CPU, do you have a BLAS library installed Theano can link against?

Traceback (most recent call last):
  File "C:\Program Files\Neuralenhance\enhance.py", line 579, in <module>
    enhancer = NeuralEnhancer(loader=False)
  File "C:\Program Files\Neuralenhance\enhance.py", line 464, in __init__
    self.model = Model()
  File "C:\Program Files\Neuralenhance\enhance.py", line 263, in __init__
    self.compile()
  File "C:\Program Files\Neuralenhance\enhance.py", line 421, in compile
    self.predict = theano.function([seed_tensor], output)
  File "C:\ProgramData\Miniconda3\lib\site-packages\theano\compile\function.py", line 309, in function
    fn = pfunc(params=inputs,
  File "C:\ProgramData\Miniconda3\lib\site-packages\theano\compile\pfunc.py", line 476, in pfunc
    return orig_function(inputs, cloned_outputs, mode,
  File "C:\ProgramData\Miniconda3\lib\site-packages\theano\compile\function_module.py", line 1770, in orig_function
    fn = Maker(inputs,
  File "C:\ProgramData\Miniconda3\lib\site-packages\theano\compile\function_module.py", line 1456, in __init__
    optimizer_profile = optimizer(fgraph)
  File "C:\ProgramData\Miniconda3\lib\site-packages\theano\gof\opt.py", line 101, in __call__
    return self.optimize(fgraph)
  File "C:\ProgramData\Miniconda3\lib\site-packages\theano\gof\opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\theano\gof\opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\ProgramData\Miniconda3\lib\site-packages\theano\gof\opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\theano\gof\opt.py", line 1879, in apply
    nb += self.process_node(fgraph, node)
  File "C:\ProgramData\Miniconda3\lib\site-packages\theano\gof\opt.py", line 1775, in process_node
    self.failure_callback(e, self,
  File "C:\ProgramData\Miniconda3\lib\site-packages\theano\gof\opt.py", line 1673, in warn_inplace
    return NavigatorOptimizer.warn(exc, nav, repl_pairs, local_opt, node)
  File "C:\ProgramData\Miniconda3\lib\site-packages\theano\gof\opt.py", line 1659, in warn
    raise exc
  File "C:\ProgramData\Miniconda3\lib\site-packages\theano\gof\opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "C:\ProgramData\Miniconda3\lib\site-packages\theano\tensor\nnet\opt.py", line 396, in local_abstractconv_check
    raise AssertionError(
AssertionError: AbstractConv2d Theano optimization failed: there is no implementation available supporting the requested options. Did you exclude both "conv_dnn" and "conv_gemm" from the optimizer? If on GPU, is cuDNN available and does the GPU support it? If on CPU, do you have a BLAS library installed Theano can link against?

**Comment by sangfrois** [comment]
I had the same problem on linux.
can someone help ? @alexjc
