### ISSUE TITLE
ImportError: cannot import name 'downsample' from 'theano.tensor.signal'

### ISSUE THREAD

**Issue by MastaG** [alexjc/neural-enhance#254]
Hi, I'm trying to run it on Fedora 33 which features Python 3.9.

But there seems to be missing a something from theano?

```
./enhance.py 
                             _              _                           
  _ __   ___ _   _ _ __ __ _| |   ___ _ __ | |__   __ _ _ __   ___ ___  
 | '_ \ / _ \ | | | '__/ _` | |  / _ \ '_ \| '_ \ / _` | '_ \ / __/ _ \ 
 | | | |  __/ |_| | | | (_| | | |  __/ | | | | | | (_| | | | | (_|  __/ 
 |_| |_|\___|\__,_|_|  \__,_|_|  \___|_| |_|_| |_|\__,_|_| |_|\___\___| 

Super Resolution for images and videos powered by Deep Learning!
  - Code licensed as AGPLv3, models under CC BY-NC-SA.
Traceback (most recent call last):
  File "/home/mastag/src/neural-enhance/./enhance.py", line 125, in <module>
    import lasagne
  File "/usr/lib/python3.9/site-packages/lasagne/__init__.py", line 19, in <module>
    from . import layers
  File "/usr/lib/python3.9/site-packages/lasagne/layers/__init__.py", line 7, in <module>
    from .pool import *
  File "/usr/lib/python3.9/site-packages/lasagne/layers/pool.py", line 6, in <module>
    from theano.tensor.signal import downsample
ImportError: cannot import name 'downsample' from 'theano.tensor.signal' (/usr/lib/python3.9/site-packages/theano/tensor/signal/__init__.py)
```

**Comment by MastaG** [comment]
nevermind fixed it by upgrading lasagne
