### ISSUE TITLE
Unable to run the command enhance --zoom=1 --model=repair images/broken.jpg

### ISSUE THREAD

**Issue by UrielMaD** [alexjc/neural-enhance#262]
When I try to run the command enhance --zoom=1 --model=repair image.png

it throws me the following error

 image.png Traceback (most recent call last):
  File "enhance.py", line 583, in <module>
    img = scipy.ndimage.imread(filename, mode='RGB')
  File "/opt/conda/lib/python3.5/site-packages/scipy/ndimage/io.py", line 24, in imread
    return _imread(fname, flatten, mode)
  File "/opt/conda/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/conda/lib/python3.5/site-packages/PIL/Image.py", line 2282, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'image.png'

I don't know if there's something related with the command 

alias enhance='function ne() { docker run --rm -v "$(pwd)/`dirname ${@:$#}`":/ne/input -it alexjc/neural-enhance ${@:1:$#-1} "input/`basename ${@:$#}`"; }; ne'

**Comment by vexaroniter** [comment]
See that, my "patch-1" branch has been removed.
Apparently the author didn't like it. Although he has not been serving this project for 4 years, what are we talking about.

Link: https://github.com/vexaroniter/neural-enhance
Pull: https://github.com/alexjc/neural-enhance/pull/260
Clone: https://github.com/vexaroniter/neural-enhance.git
