### ISSUE TITLE
Training with data TypeError

### ISSUE THREAD

**Issue by hemel-cse** [alexjc/neural-enhance#39]
![screenshot from 2016-11-01 19-03-15](https://cloud.githubusercontent.com/assets/6664461/19890578/de63945e-a065-11e6-894e-c3c101923f72.png)

**Comment by alexjc** [comment]
Please don't submit screenshots. Can you paste the text?

**Comment by hemel-cse** [comment]
hemel@hulk:~/github/neural-enhance$ python3 enhance.py --train "data/*.jpg" --model custom --scales=2 --epochs=50     --perceptual-layer=conv2_2 --smoothness-weight=1e7 --adversary-weight=0.0     --generator-blocks=4 --generator-filters=64
                             _              _                           
  _ __   ___ _   _ _ __ __ _| |   ___ _ __ | |__   __ _ _ __   ___ ___  
 | '_ \ / _ \ | | | '__/ _` | |  / _ \ '_ \| '_ \ / _` | '_ \ / __/ _ \ 
 | | | |  __/ |_| | | | (_| | | |  __/ | | | | | | (_| | | | | (_|  __/ 
 |_| |_|\___|\__,_|_|  \__,_|_|  \___|_| |_|_| |_|\__,_|_| |_|\___\___| 

Super Resolution for images and videos powered by Deep Learning!
  - Code licensed as AGPLv3, models under CC BY-NC-SA.
  - Using the device `cpu` for neural computation.

Training 50 epochs on random image sections with batch size 15.
Traceback (most recent call last):
  File "enhance.py", line 512, in <module>
    enhancer = NeuralEnhancer()
  File "enhance.py", line 429, in __init__
    self.model = Model()
  File "enhance.py", line 230, in __init__
    self.load_perceptual()
  File "enhance.py", line 332, in load_perceptual
    for p, d in zip(itertools.chain(*[l.get_params() for l in layers]), data): p.set_value(d)
  File "/home/hemel/.local/lib/python3.5/site-packages/theano/compile/sharedvalue.py", line 127, in set_value
    self.container.value = copy.deepcopy(new_value)
  File "/home/hemel/.local/lib/python3.5/site-packages/theano/gof/link.py", line 468, in __set__
    self.storage[0] = self.type.filter(value, **kwargs)
  File "/home/hemel/.local/lib/python3.5/site-packages/theano/tensor/type.py", line 149, in filter
    converted_data = theano._asarray(data, self.dtype)
  File "/home/hemel/.local/lib/python3.5/site-packages/theano/misc/safe_asarray.py", line 33, in _asarray
    rval = numpy.asarray(a, dtype=dtype, order=order)
  File "/home/hemel/.local/lib/python3.5/site-packages/numpy/core/numeric.py", line 482, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: ("float() argument must be a string or a number, not 'dict'", 'Container name "None"')
hemel@hulk:~/github/neural-enhance$

**Comment by alexjc** [comment]
Is your `vgg19_conv.pkl.bz2` downloaded correctly? It's MD5 sum is `21b459c447da87468f2db9b6130380eb`.
