### ISSUE TITLE
Docker exemple is invalid

### ISSUE THREAD

**Issue by urschuca** [alexjc/neural-enhance#72]
Hi,

I just install the docker image by following your instruction and I get an error when I try to run it : 

```
root@golgoth Ω Images :# pwd
/home/gauthier/Images
root@golgoth Ω Images :# ls enhance 
exemple.jpg
root@golgoth Ω Images :# enhance --zoom=2 enhance/example.jpg                     
...
enhance/example.jpg Traceback (most recent call last):
  File "enhance.py", line 583, in <module>
    img = scipy.ndimage.imread(filename, mode='RGB')
  File "/opt/conda/lib/python3.5/site-packages/scipy/ndimage/io.py", line 24, in imread
    return _imread(fname, flatten, mode)
  File "/opt/conda/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/conda/lib/python3.5/site-packages/PIL/Image.py", line 2282, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'enhance/example.jpg'

```

What do I need to do to run enhance ?

**Comment by alexjc** [comment]
@urschuca Does `--help` work as a parameter for enhance on its own? What's your shell choice?

**Comment by urschuca** [comment]
--help fails. I test on zsh and on bash. Same results : 

```
[root@golgoth Ω ~]# alias enhance='function ne() { docker run --rm -v "$(pwd)/`dirname ${@:$#}`":/ne/input -it alexjc/neural-enhance ${@:1:$#-1} "input/`basename ${@:$#}`"; }; ne'
[root@golgoth Ω ~]# enhance --help
docker: Error response from daemon: Invalid bind mount spec "/root/Utilisation\u00a0: dirname [OPTION] NOM...\nAfficher chaque NOM en supprimant son dernier composant et sa barre oblique\nfinale\u00a0; si NOM ne contient pas de «\u00a0/\u00a0», la sortie sera «\u00a0.\u00a0» (signifiant\nle répertoire actuel).\n\n  -z, --zero     terminer chaque ligne de sortie par NULL, pas un changement\n                         de ligne\n      --help     afficher l'aide et quitter\n      --version  afficher des informations de version et quitter\n\nExemples\u00a0:\n  dirname /usr/bin           → «\u00a0/usr\u00a0»\n  dirname rep1/cha rep2/cha  → «\u00a0rep1\u00a0» suivi de «\u00a0rep2\u00a0»\n  dirname stdio.h            → «\u00a0.\u00a0»\n\nAide en ligne de GNU coreutils\u00a0: <http://www.gnu.org/software/coreutils/>\nSignalez les problèmes de traduction de «\u00a0dirname\u00a0» à\u00a0: <traduc@traduc.org>\nFull documentation at: <http://www.gnu.org/software/coreutils/dirname>\nor available locally via: info '(coreutils) dirname invocation':/ne/input": Invalid volume specification: '/root/Utilisation : dirname [OPTION] NOM...
Afficher chaque NOM en supprimant son dernier composant et sa barre oblique
finale ; si NOM ne contient pas de « / », la sortie sera « . » (signifiant
le répertoire actuel).

  -z, --zero     terminer chaque ligne de sortie par NULL, pas un changement
                         de ligne
      --help     afficher l'aide et quitter
      --version  afficher des informations de version et quitter

Exemples :
  dirname /usr/bin           → « /usr »
  dirname rep1/cha rep2/cha  → « rep1 » suivi de « rep2 »
  dirname stdio.h            → « . »

Aide en ligne de GNU coreutils : <http://www.gnu.org/software/coreutils/>
Signalez les problèmes de traduction de « dirname » à : <traduc@traduc.org>
Full documentation at: <http://www.gnu.org/software/coreutils/dirname>
or available locally via: info '(coreutils) dirname invocation':/ne/input'.
See 'docker run --help'.
```

**Comment by alexjc** [comment]
OK, that's another bug :-| How does the manual `docker run` command from the README work?

**Comment by urschuca** [comment]
It works fine : 

```
[root@golgoth Ω ~]# docker run --rm -v `pwd`:/ne/input -it alexjc/neural-enhance --help
usage: enhance.py [-h] [--zoom ZOOM] [--rendering-tile RENDERING_TILE]
                  [--rendering-overlap RENDERING_OVERLAP]
                  ...
```

I dont know docker well, but maybe its just a problem with the syntax of the alias ?

**Comment by alexjc** [comment]
Yes, it's definitely an alias problem. Can you try this command:

```docker run --rm -v `pwd`:/ne/input -it alexjc/neural-enhance --zoom=2 input/example.jpg```

Assuming `example.jpg` is in your current folder.

**Comment by urschuca** [comment]
It seems to work

**Comment by alexjc** [comment]
@urschuca Thanks for your help. Last check... can you replace the `docker` command inside the alias with `echo docker` and paste the output?

**Comment by urschuca** [comment]
This way : 

```
[root@golgoth Ω enhance]# alias enhance='function ne() { echo docker run --rm -v "$(pwd)/`dirname ${@:$#}`":/ne/input -it alexjc/neural-enhance ${@:1:$#-1} "input/`basename ${@:$#}`"; }; ne'
[root@golgoth Ω enhance]# enhance
dirname: opérande manquant
Saisissez « dirname --help » pour plus d'informations.
basename: opérande manquant
Saisissez « basename --help » pour plus d'informations.
docker run --rm -v /home/gauthier/Images/enhance/:/ne/input -it alexjc/neural-enhance input/
```

**Comment by alexjc** [comment]
Yeah, with ```enhance --zoom=2 enhance/example.jpg```

**Comment by urschuca** [comment]
```
[root@golgoth Ω Images]# pwd
/home/gauthier/Images
[root@golgoth Ω Images]# enhance --zoom=2 enhance/treant.jpg
docker run --rm -v /home/gauthier/Images/enhance:/ne/input -it alexjc/neural-enhance --zoom=2 input/treant.jpg
```

**Comment by alexjc** [comment]
Very strange, it looks like everything should work and I can't explain this error above:
```FileNotFoundError: [Errno 2] No such file or directory: 'enhance/example.jpg'```

The `--help` thing is a bug though.

**Comment by urschuca** [comment]
Very strange I renew the alias by removing "echo" : 

root@golgoth Ω Images]# alias enhance='function ne() { docker run --rm -v "$(pwd)/`dirname ${@:$#}`":/ne/input -it alexjc/neural-enhance ${@:1:$#-1} "input/`basename ${@:$#}`"; }; ne'

And now its work

[root@golgoth Ω Images]# enhance --zoom=2 enhance/treant.jpg
...

But the --help still fail.

**Comment by alexjc** [comment]
OK, I'll leave this ticket open until I fix the alias to heal with `--help`.
