### ISSUE TITLE
Killed when running as Docker image

### ISSUE THREAD

**Issue by rhuss** [alexjc/neural-enhance#8]
When running as a Docker image on Docker for Mac 1.12.3, the process gets killed after a certain 

time:

```
$ docker run -v $(pwd)/images:/ne/images -it --entrypoint bash alexjc/neural-enhance
root@19242636a424:/ne# /opt/conda/bin/python3.5 enhance.py --device=cpu images/roland_test.jpg
                             _              _
  _ __   ___ _   _ _ __ __ _| |   ___ _ __ | |__   __ _ _ __   ___ ___
 | '_ \ / _ \ | | | '__/ _` | |  / _ \ '_ \| '_ \ / _` | '_ \ / __/ _ \
 | | | |  __/ |_| | | | (_| | | |  __/ | | | | | | (_| | | | | (_|  __/
 |_| |_|\___|\__,_|_|  \__,_|_|  \___|_| |_|_| |_|\__,_|_| |_|\___\___|

Super Resolution for images and videos powered by Deep Learning!
  - Code licensed as AGPLv3, models under CC BY-NC-SA.
  - Using the device `cpu` for neural computation.

Enhancing 1 image(s) specified on the command-line.
  - Loaded file `ne4x-medium-0.1.pkl.bz2` with trained model.

images/roland_test.jpg
Killed
root@19242636a424:/ne#
```

**Comment by xuyifeng-nwpu** [comment]
I have the similar problem . Thirty minutes passed away, but the message still was "images/sample.jpg"

**Comment by crsrusl** [comment]
Same issue here

**Comment by markoshust** [comment]
I'm getting a little more verbose output:

```
Marks-MacBook-Air-2:Desktop markshust$ enhance Screen\ Shot\ 2016-11-03\ at\ 3.12.14\ PM.png 
usage: dirname path
                             _              _                           
  _ __   ___ _   _ _ __ __ _| |   ___ _ __ | |__   __ _ _ __   ___ ___  
 | '_ \ / _ \ | | | '__/ _` | |  / _ \ '_ \| '_ \ / _` | '_ \ / __/ _ \ 
 | | | |  __/ |_| | | | (_| | | |  __/ | | | | | | (_| | | | | (_|  __/ 
 |_| |_|\___|\__,_|_|  \__,_|_|  \___|_| |_|_| |_|\__,_|_| |_|\___\___| 

Super Resolution for images and videos powered by Deep Learning!
  - Code licensed as AGPLv3, models under CC BY-NC-SA.
  - Using the device `cpu` for neural computation.

Enhancing 6 image(s) specified on the command-line.
  - Loaded file `ne4x-small-0.1.pkl.bz2` with trained model.

input/Screen
Traceback (most recent call last):
  File "enhance.py", line 519, in <module>
    img = scipy.ndimage.imread(filename, mode='RGB')
  File "/opt/conda/lib/python3.5/site-packages/scipy/ndimage/io.py", line 24, in imread
    return _imread(fname, flatten, mode)
  File "/opt/conda/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/conda/lib/python3.5/site-packages/PIL/Image.py", line 2282, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'input/Screen'
```

**Comment by alexjc** [comment]
Try again with version 0.2, it includes the tiled rendering options! If there's a problem open a new issue.

**Comment by AbbasEl-Bourji** [comment]
Hello, Please go to Play Store and update the App, in the new update
version do you can download photos, videos and documents. If you update the
App you DON’T need to rescan the QR code again!  And if you have android
version 5.0 and up then the size of the app is after the update only 9 mb.
Please give us 5 stars and a good review my friend. Have fun with the App !
